# Default values for blackbox-exporter.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 1

image:
  repository: quay.io/prometheus/blackbox-exporter
  pullPolicy: Always
  # Overrides the image tag whose default is the chart appVersion.
  tag: "latest"

service:
  type: ClusterIP
  port: 9115

  hosts:
    - host: blackbox-exporter.local
      paths:
        - path: /
          pathType: ImplementationSpecific
  tls: []
  #  - secretName: chart-example-tls
  #    hosts:
  #      - chart-example.local



# configBlackboxExporter, es el archivo de configuracion de blackbox-exporter, este es un ejemplo 
configBlackboxExporter: |
        scrape_configs:
          - job_name: 'blackbox'
            metrics_path: /probe
            params:
              module: [http_2xx]  # Look for a HTTP 200 response.
            static_configs:
              - targets:
                - https://google.com 
                - https://prometheus.io 
                - http://192.168.100.18 
                - https://www.apple.com
            relabel_configs:
              - source_labels: [__address__]
                target_label: __param_target
              - source_labels: [__param_target]
                target_label: instance
              - target_label: __address__
                replacement: 127.0.0.1:9115  # The blackbox exporter's real hostname:port.