apiVersion: v1
entries:
  acme:
  - apiVersion: v2
    appVersion: 1.16.0
    created: "2023-01-02T23:56:10.555058494-03:00"
    description: Acme demo chart for kubernetes
    digest: 44dd49000d481afbc5902c8ff37f8da84f91a5ab154020c5e06202057a4c85de
    name: acme
    type: application
    urls:
    - https://kurobatou.github.io/helmchart-kurobatou/charts/acme-0.1.0.tgz
    version: 0.1.0
  blackbox-exporter:
  - apiVersion: v2
    appVersion: 1.18.0
    created: "2023-01-02T23:56:10.555815672-03:00"
    description: A char with a blackbox-exporter with some configurations on values.yaml
    digest: 63e981604b4eb2b411f41ffca5e2d8b95f5ac030b88a8064100e5593a8f512b6
    name: blackbox-exporter
    type: application
    urls:
    - https://kurobatou.github.io/helmchart-kurobatou/charts/blackbox-exporter-0.1.1.tgz
    version: 0.1.1
  - apiVersion: v2
    appVersion: 1.17.0
    created: "2023-01-02T23:56:10.555457483-03:00"
    description: A char with a blackbox-exporter with some configurations on values.yaml
    digest: 8ab88cda2c0e27638547f7db422d4d8130fba087f08201971a40fb4fc2eab764
    name: blackbox-exporter
    type: application
    urls:
    - https://kurobatou.github.io/helmchart-kurobatou/charts/blackbox-exporter-0.1.0.tgz
    version: 0.1.0
generated: "2023-01-02T23:56:10.554516905-03:00"
